### ISSUE TITLE
Elección de un lenguaje de programación

### ISSUE THREAD

**Issue by shvtwp** [marinajcs/asignacionTareas#6]
Hola, me han asignado tu proyecto. Lo primero es elegir un lenguaje de programación. Yo consideraría oportuno que fuese un lenguaje en el que se puedan definir estructuras de datos, y fuertemente tipado, ya que facilitaría el manejo de excepciones. ¿Qué te parece TypeScript?¿Tienes alguna otra sugerencia?

**Comment by marinajcs** [comment]
> Hola, me han asignado tu proyecto. Lo primero es elegir un lenguaje de programación. Yo consideraría oportuno que fuese un lenguaje en el que se puedan definir estructuras de datos, y fuertemente tipado, ya que facilitaría el manejo de excepciones. ¿Qué te parece TypeScript?¿Tienes alguna otra sugerencia?

Buenas, había pensado inicialmente Ruby o JavaScript, pero teniendo en cuenta lo que has dicho y que TypeScript es popular debido a su escalabilidad, seguridad y documentación, me parece una opción interesante y adecuada 👌

**Comment by shvtwp** [comment]
Perfecto, TypeScript entonces
