### ISSUE TITLE
¿Qué son los compañeros de piso?

### ISSUE THREAD

**Issue by shvtwp** [marinajcs/asignacionTareas#8]
- Son personas que comparten un piso.
- Tienen que dividirse las tareas domésticas.
- Tienen un número concreto de horas disponibles a la semana.

Contemplado en la #2

**Comment by JJ** [comment]
Un issue debe abordar una sola HU, si no se hace todo muy complicado.
También empezar por "entidades" te cierra en una solución específica al problema, obligándote a crear un objeto que lo represente, mientras que puede o no ser solución al problema.

**Comment by JJ** [comment]
Por favor, no cerréis desde el formulario. Siempre hay que cerrar desde un commit o PR; en este caso lo mejor es una serie de "closes" al final del cuerpo del PR que diga que se cierran porque no están planificados.
